name: build

on:
  push:
    branches:
      - master

jobs:
  build-job:
    if: github.event_name == 'push' && contains(toJson(github.event.commits), '[ci skip]') == false
    strategy:
      matrix:
        profile: [ rpi, rpizero, nclassic, psclassic, armv6l, armv7l, arm64 ]
        packager: [ npm, yarn ]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 15.6.0

      - name: Linux Packages
        if: contains(matrix.profile, 'arm64')
        run: sudo apt-get install -y g++-6-aarch64-linux-gnu
        shell: bash

      - name: Run cross on package with native compilation
        run: ../bin/cross ${{ matrix.profile }} ${{ matrix.packager }} install
        shell: bash
        working-directory: test

